ERROR - 2023-08-21 01:40:46 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it.
 in C:\xampp\htdocs\sop_apk\system\Database\MySQLi\Connection.php:174
Stack trace:
#0 C:\xampp\htdocs\sop_apk\system\Database\MySQLi\Connection.php(174): mysqli->real_connect('localhost', 'root', '', 'db', 3306, '', 0)
#1 C:\xampp\htdocs\sop_apk\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\sop_apk\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\sop_apk\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\sop_apk\system\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\sop_apk\system\BaseModel.php(656): CodeIgniter\Model->doFirst()
#6 C:\xampp\htdocs\sop_apk\app\Validation\AuthRules.php(31): CodeIgniter\BaseModel->first()
#7 C:\xampp\htdocs\sop_apk\system\Validation\Validation.php(278): App\Validation\AuthRules->validateUser('riko21', 'email,password', Array, NULL, 'password')
#8 C:\xampp\htdocs\sop_apk\system\Validation\Validation.php(182): CodeIgniter\Validation\Validation->processRules('password', 'password', 'riko21', Array, Array)
#9 C:\xampp\htdocs\sop_apk\system\Controller.php(140): CodeIgniter\Validation\Validation->run()
#10 C:\xampp\htdocs\sop_apk\app\Controllers\Auth.php(76): CodeIgniter\Controller->validate(Array, Array)
#11 C:\xampp\htdocs\sop_apk\system\CodeIgniter.php(932): App\Controllers\Auth->login()
#12 C:\xampp\htdocs\sop_apk\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#13 C:\xampp\htdocs\sop_apk\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#14 C:\xampp\htdocs\sop_apk\public\index.php(67): CodeIgniter\CodeIgniter->run()
#15 C:\xampp\htdocs\sop_apk\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#16 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it.
 in C:\xampp\htdocs\sop_apk\system\Database\MySQLi\Connection.php:218
Stack trace:
#0 C:\xampp\htdocs\sop_apk\system\Database\BaseConnection.php(391): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\sop_apk\system\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\sop_apk\system\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\sop_apk\system\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\sop_apk\system\BaseModel.php(656): CodeIgniter\Model->doFirst()
#5 C:\xampp\htdocs\sop_apk\app\Validation\AuthRules.php(31): CodeIgniter\BaseModel->first()
#6 C:\xampp\htdocs\sop_apk\system\Validation\Validation.php(278): App\Validation\AuthRules->validateUser('riko21', 'email,password', Array, NULL, 'password')
#7 C:\xampp\htdocs\sop_apk\system\Validation\Validation.php(182): CodeIgniter\Validation\Validation->processRules('password', 'password', 'riko21', Array, Array)
#8 C:\xampp\htdocs\sop_apk\system\Controller.php(140): CodeIgniter\Validation\Validation->run()
#9 C:\xampp\htdocs\sop_apk\app\Controllers\Auth.php(76): CodeIgniter\Controller->validate(Array, Array)
#10 C:\xampp\htdocs\sop_apk\system\CodeIgniter.php(932): App\Controllers\Auth->login()
#11 C:\xampp\htdocs\sop_apk\system\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
#12 C:\xampp\htdocs\sop_apk\system\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 C:\xampp\htdocs\sop_apk\public\index.php(67): CodeIgniter\CodeIgniter->run()
#14 C:\xampp\htdocs\sop_apk\system\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs...')
#15 {main}
CRITICAL - 2023-08-21 01:40:46 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it.

in SYSTEMPATH\Database\BaseConnection.php on line 427.
 1 SYSTEMPATH\Database\BaseConnection.php(574): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1616): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`
WHERE `email` = :email:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(268): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(656): CodeIgniter\Model->doFirst()
 5 APPPATH\Validation\AuthRules.php(31): CodeIgniter\BaseModel->first()
 6 SYSTEMPATH\Validation\Validation.php(278): App\Validation\AuthRules->validateUser('riko21', 'email,password', [...], null, 'password')
 7 SYSTEMPATH\Validation\Validation.php(182): CodeIgniter\Validation\Validation->processRules('password', 'password', 'riko21', [...], [...])
 8 SYSTEMPATH\Controller.php(140): CodeIgniter\Validation\Validation->run()
 9 APPPATH\Controllers\Auth.php(76): CodeIgniter\Controller->validate([...], [...])
10 SYSTEMPATH\CodeIgniter.php(932): App\Controllers\Auth->login()
11 SYSTEMPATH\CodeIgniter.php(497): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Auth))
12 SYSTEMPATH\CodeIgniter.php(366): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Commands\Server\rewrite.php(47): require_once('C:\\xampp\\htdocs\\sop_apk\\public\\index.php')
